#!/usr/bin/env bash
# Lists paths to upload when hardening module architecture.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "== Deploy: module architecture hardening =="
echo ""
echo "Upload the entire WebinaDashboard/ plugin (modules live inside it):"
echo ""
echo "  wp-content/plugins/WebinaDashboard/"
echo "    webino-dashboard.php"
echo "    includes/"
echo "    Modules/   (all extension modules)"
echo "    assets/dashboard-build/"
echo ""
echo "After upload, remove obsolete sibling if present:"
echo "  rm -rf wp-content/plugins/Modules"
echo ""
echo "Recovery if a single module fatals:"
echo "  mv wp-content/plugins/WebinaDashboard/Modules/telegram-bot-module \\"
echo "     wp-content/plugins/WebinaDashboard/Modules/telegram-bot-module.off"
echo ""
echo "Verify after deploy:"
echo "  curl -sI https://YOUR-SITE/wp-json/ | head -1"
echo "  curl -sI https://YOUR-SITE/wp-json/webino-dashboard/v1/auth/session | head -1"
echo ""
echo "Local smoke:"
echo "  bash \"$ROOT/scripts/smoke-modules-structure.sh\""
echo "  bash \"$ROOT/scripts/smoke-module-routes.sh\""
