#!/usr/bin/env bash
# Lists paths to upload when hardening module architecture.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "== Deploy: module architecture hardening =="
echo ""
echo "For the shared ESM runtime fix (h is not a function), use the atomic package:"
echo "  bash \"$ROOT/scripts/deploy-shared-runtime.sh\""
echo "  # optional remote:"
echo "  WEBINO_DEPLOY_RSYNC='user@host:/path/wp-content/plugins/WebinaDashboard' \\"
echo "    bash \"$ROOT/scripts/deploy-shared-runtime.sh\""
echo ""
echo "Upload together (incomplete = modules keep failing):"
echo "  assets/dashboard-build/   # MUST include shared/ + build-entry.json"
echo "  Modules/*/client/dist/"
echo "  includes/class-webino-dashboard-assets.php"
echo ""
echo "Or upload the entire WebinaDashboard/ plugin:"
echo "  wp-content/plugins/WebinaDashboard/"
echo "    webino-dashboard.php"
echo "    includes/"
echo "    Modules/"
echo "    assets/dashboard-build/"
echo ""
echo "After upload, remove obsolete sibling if present:"
echo "  rm -rf wp-content/plugins/Modules"
echo ""
echo "Verify after deploy:"
echo "  bash \"$ROOT/scripts/verify-live-shared-runtime.sh https://YOUR-SITE\""
echo "  curl -sI https://YOUR-SITE/wp-json/ | head -1"
echo ""
echo "Local smoke:"
echo "  bash \"$ROOT/scripts/smoke-modules-structure.sh\""
echo "  bash \"$ROOT/scripts/smoke-module-routes.sh\""
