#!/usr/bin/env bash
# Lists paths to upload when hardening module architecture (fixes activation 500 on sites
# that still have legacy telegram bootstrap or full Modules/* copied from repo).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"

echo "== Deploy: module architecture hardening =="
echo ""
echo "Upload these paths relative to wp-content/plugins/ (adjust if your layout differs):"
echo ""
echo "WebinoDashboard/"
echo "  webino-dashboard.php"
echo "  includes/class-webino-dashboard-module-registry.php  (REQUIRED: legacy bootstrap guard + init load)"
echo "  includes/class-webino-dashboard-rest-marketplace.php  (uninstall order fix)"
echo "  includes/class-webino-dashboard-bootstrap.php  (guarded core loader)"
echo "  includes/bots/   (entire directory)"
echo ""
echo "Minimum to recover parisma when old telegram bootstrap remains on disk:"
echo "  Upload ONLY class-webino-dashboard-module-registry.php — unsafe bootstrap is auto-deactivated."
echo ""
echo "Modules/ (only if installed on the site via marketplace — do NOT copy entire repo Modules/)"
echo "  telegram-bot-module/bootstrap.php"
echo "  telegram-bot-module/manifest.json"
echo "  telegram-bot-module/includes/class-webino-dashboard-telegram-bot-loader.php"
echo "  bale-bot-module/bootstrap.php"
echo "  bale-bot-module/includes/   (stubs + engine if present)"
echo "  wfcp-module/includes/class-webino-dashboard-wfcp-loader.php"
echo ""
echo "Recovery if site is down before deploy:"
echo "  mv wp-content/plugins/Modules/telegram-bot-module wp-content/plugins/Modules/telegram-bot-module.off"
echo ""
echo "Verify after deploy:"
echo "  curl -sI https://YOUR-SITE/wp-json/ | head -1"
echo "  curl -sI https://YOUR-SITE/wp-json/webino-dashboard/v1/auth/session | head -1"
echo "  (expect 200 or 401 for session — not 500)"
echo ""
echo "Local smoke:"
echo "  bash \"$ROOT/scripts/smoke-modules-structure.sh\""
echo "  php \"$ROOT/scripts/test-bootstrap-guard.php\""
echo "  php \"$ROOT/scripts/test-incomplete-module-package.php\""
